site_name: Ainazar Docs
#extra_css:
#  - stylesheets/extra.css
theme:
  name: material
  features:
  #  - navigation.tabs
  #  - navigation.instant
    - navigation.top
    - header.autohide
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: yellow
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
- Home: index.md
- Tutorial:
    - First steps: tutorial/first_steps.md

plugins:
  - search
  - i18n:
      default_language: en
      docs_structure: folder
      languages:
        en:
          name: English
        ru:
          name: Русский
          site_name: Документация Айназара
      nav_translations:
        ru:
          Home: Домашняя
          Tutorial: Обучение
          First steps: Первые шаги

markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- attr_list
- md_in_html
